export const INTERACTIVE='a[href],button,input:not([type=hidden]),select,textarea,[role=button],[role=link],[role=checkbox],[role=radio],[role=tab],[role=menuitem],[role=switch],[tabindex]';
export function ownedElement(element:Element){let node:Node|null=element;while(node){if(node instanceof Element&&(node.hasAttribute('data-accesslab-root')||node.hasAttribute('data-accesslab-overlay')))return true;node=node.parentNode??(node instanceof ShadowRoot?node.host:null);}return false;}
export function elementPath(element:Element){const segments:string[]=[];let current:Element|null=element;
 while(current&&segments.length<32){const root=current.getRootNode();const id=current.id;if(id){segments.unshift('#'+CSS.escape(id));}else{const siblings=current.parentElement?[...current.parentElement.children].filter(e=>e.tagName===current!.tagName):[current];segments.unshift(`${current.tagName.toLowerCase()}:nth-of-type(${siblings.indexOf(current)+1})`);}
 if(id){if(root instanceof ShadowRoot){segments.unshift('→');current=root.host;continue;}break;}current=current.parentElement??(root instanceof ShadowRoot?root.host:null);
 }return segments.join(' > ').replaceAll(' > → > ',' → ');
}
export function candidates(document:Document){const results:Element[]=[];const roots:(Document|ShadowRoot)[]=[document];while(roots.length){const root=roots.pop()!;for(const e of root.querySelectorAll(INTERACTIVE))if(!ownedElement(e))results.push(e);for(const e of root.querySelectorAll('*'))if(e.shadowRoot&&!ownedElement(e))roots.push(e.shadowRoot);}return results;}
export function visibleTarget(element:Element){if(ownedElement(element)||element.matches(':disabled,[aria-disabled=true]')||element.closest('[hidden],[inert],[aria-hidden=true]'))return false;const style=getComputedStyle(element),rect=element.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&style.visibility!=='collapse'&&rect.width>0&&rect.height>0&&element.getClientRects().length>0;}
