import { useState,useMemo } from 'react';
import type { AuditReport } from '@accesslab/contracts';
import type { PageController } from '../runtime/controller';
import { serializeReport } from '../export/report';
export function Export({report,controller}:{report:AuditReport;controller:PageController}){
 const [format,setFormat]=useState<'json'|'markdown'>('json'),[include,setInclude]=useState(false),[show,setShow]=useState(false),[error,setError]=useState('');const state=controller.getState();const observations=include?state.observations:undefined,focus=include?state.focusTrail:undefined,truncated=include?state.targetTruncated:undefined;
 const {text,failure}=useMemo(()=>{try{return{text:serializeReport(report,format,observations&&focus?{targets:observations,focus,omittedTargetCandidates:truncated??0}:undefined),failure:''};}catch(e){return{text:'',failure:String(e)};}},[report,format,observations,focus,truncated]);
 function download(){if(failure)return;const url=URL.createObjectURL(new Blob([text],{type:format==='json'?'application/json':'text/markdown;charset=utf-8'}));const a=controller.document.createElement('a');a.href=url;a.download=`accesslab-report.${format==='json'?'json':'md'}`;a.click();const cleanup=controller.effects.add(()=>{clearTimeout(timer);URL.revokeObjectURL(url);});const timer=setTimeout(()=>{void cleanup()},1000);setError('');}
 return <details><summary>Export report</summary><p>Local download only. URL query, fragment, title, page text, input values and HTML are omitted. Locators may reveal identifiers and page structure. Review before sharing.</p><label>Export format <select value={format} onChange={e=>setFormat(e.target.value as 'json'|'markdown')}><option value="json">JSON</option><option value="markdown">Markdown</option></select></label><label><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)}/> Include inspection observations separately</label><div className="row"><button onClick={()=>setShow(!show)}>{show?'Hide export preview':'Preview export'}</button><button disabled={!!failure} onClick={()=>{try{download()}catch(e){setError(String(e))}}}>Download report</button></div>{show&&!failure&&<><label htmlFor="export-preview">Export preview</label><textarea id="export-preview" aria-label="Export preview" className="export" readOnly rows={8} value={text}/></>}{(failure||error)&&<p role="alert">{failure||error}</p>}</details>;
}
