import { useState } from 'react';
import type { AuditReport, Finding } from '@accesslab/contracts';
import type { PageController } from '../runtime/controller';
export function filtered(findings:Finding[],impact:string){return findings.filter(f=>impact==='all'||(f.impact??'unspecified')===impact);}
function safeHelpUrl(href:string){try{const url=new URL(href);return url.protocol==='https:'&&url.hostname==='dequeuniversity.com'?href:undefined;}catch{return undefined;}}
function FindingPage({rows,label,controller}: {rows:Finding[];label:string;controller:PageController}){
 const [page,setPage]=useState(0);const perPage=50;const start=page*perPage;
 return <section aria-label={label}><h3>{label} ({rows.length})</h3>{rows.length===0&&<p className="muted">No findings match this filter.</p>}{rows.slice(start,start+perPage).map(f=><article className="finding" key={f.id} data-finding-id={f.id}><h3>{f.help}</h3><span className="badge">{f.impact??'Unspecified impact'}</span><p className="target">{f.target.join(' → ')}</p><details><summary>Explanation and fix guidance</summary><p>{f.explanation}</p><p>{f.suggestion}</p><p className="muted">Rule: {f.ruleId} · {f.tags.join(', ')}</p>{safeHelpUrl(f.helpUrl)&&<a href={safeHelpUrl(f.helpUrl)} target="_blank" rel="noopener noreferrer">Official rule guidance</a>}<p className="muted">Review the suggestion in context; it is not an automatic repair.</p></details><div className="row"><button onClick={()=>controller.locateFinding(f.id)}>Locate target</button><button onClick={()=>controller.focusFinding(f.id)}>Focus target</button></div></article>)}{rows.length>perPage&&<div className="row"><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous {label.toLowerCase()}</button><span>{start+1}–{Math.min(start+perPage,rows.length)} of {rows.length}</span><button disabled={start+perPage>=rows.length} onClick={()=>setPage(page+1)}>Next {label.toLowerCase()}</button></div>}</section>;
}
export function Findings({report,controller}: {report:AuditReport;controller:PageController}){
 const [impact,setImpact]=useState('all'),[review,setReview]=useState('both');
 return <><div className="row"><label>Severity <select aria-label="Severity" value={impact} onChange={e=>setImpact(e.target.value)}>{['all','critical','serious','moderate','minor','unspecified'].map(x=><option value={x} key={x}>{x==='all'?'All severities':x}</option>)}</select></label><label>Review status <select aria-label="Review status" value={review} onChange={e=>setReview(e.target.value)}><option value="both">Findings and needs review</option><option value="violation">Automated findings</option><option value="needs-review">Needs review</option></select></label></div>{report.violations.length===0&&<p>No automated issues found in the scanned scope; manual checks remain.</p>}{review!=='needs-review'&&<FindingPage key={`v-${report.generation}-${impact}`} rows={filtered(report.violations,impact)} label="Findings" controller={controller}/>}{review!=='violation'&&<FindingPage key={`r-${report.generation}-${impact}`} rows={filtered(report.needsReview,impact)} label="Needs review" controller={controller}/>}</>;
}
