import { test, expect } from './fixture';
import { readState } from './state';
test('bundled audit finds broken controls, includes open shadows, excludes frames/UI and fixed pair removes findings',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).report?.violations.some(f=>f.ruleId==='button-name')).toBe(true);
 let report=(await readState(worker,page.url())).report!;expect(report.engine.name).toBe('axe-core');expect(report.scope.excludedFrames).toBe(1);expect(report.violations.some(f=>f.target.includes('#unlabeled'))).toBe(true);expect(report.violations.some(f=>f.ruleId==='image-alt')).toBe(true);expect(report.violations.some(f=>f.ruleId==='label')).toBe(true);expect(report.violations.some(f=>f.target.some(t=>t.includes('shadow-button')))).toBe(true);expect(report.violations.some(f=>f.target.join(' ').includes('accesslab'))).toBe(false);expect(report.violations.some(f=>f.target.join(' ').includes('frame-broken'))).toBe(false);
 await page.locator('#fixed').check();await expect.poll(async()=>(await readState(worker,page.url())).status).toBe('stale');await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).report?.generation).toBeGreaterThan(report.generation);report=(await readState(worker,page.url())).report!;expect(report.violations.filter(f=>['button-name','label','image-alt'].includes(f.ruleId))).toEqual([]);
});
test('reset and cancel prevent late audit publication without stealing focus',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('button',{name:'Run audit',exact:true}).click();await page.getByRole('button',{name:'Reset',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).status).toBe('idle');expect((await readState(worker,page.url())).report).toBeUndefined();await expect(page.getByRole('button',{name:'Reset',exact:true})).toBeFocused();
});

test('large page audit fails explicitly before blocking the panel',async({page,activate,worker})=>{await page.goto('http://127.0.0.1:4173/?large');await activate(page);await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).status).toBe('error');await expect(page.getByRole('status')).toContainText('AUDIT_SCOPE_TOO_LARGE');expect((await readState(worker,page.url())).report).toBeUndefined();await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.getByRole('status')).toContainText('Reset complete');});
test('open-shadow mutations stale reports and oversized open-shadow fixtures fail explicitly',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).report?.generation??0).toBeGreaterThan(0);
 await page.evaluate(()=>document.querySelector('#open-shadow')!.shadowRoot!.querySelector('#nested-shadow')!.shadowRoot!.querySelector('button')!.setAttribute('aria-label','Changed shadow label'));await expect.poll(async()=>(await readState(worker,page.url())).report?.stale).toBe(true);
 await page.evaluate(()=>{const host=document.createElement('div');document.body.append(host);host.attachShadow({mode:'open'}).innerHTML='<button>Shadow control</button>'.repeat(1001)});await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).status).toBe('error');await expect(page.getByRole('status')).toContainText('including open shadow roots');
});
