import { test, expect } from './fixture';
import { readState } from './state';
test('findings locate the actual target, preserve scan focus and reject a replaced element',async({page,activate,worker},info)=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);const run=page.getByRole('button',{name:'Run audit',exact:true});await run.click();await expect.poll(async()=>(await readState(worker,page.url())).report?.violations.length??0).toBeGreaterThan(0);await expect(run).toBeFocused();
 const finding=(await readState(worker,page.url())).report!.violations.find(f=>f.target.includes('#unlabeled'))!;const row=page.locator(`[data-finding-id="${finding.id}"]`);await row.locator('summary').click();await expect(row).toContainText('accessible name');await row.getByRole('button',{name:'Locate target',exact:true}).click();const target=await page.locator('#unlabeled').boundingBox();const outline=await page.locator('[data-accesslab-overlay] .outline').boundingBox();expect(outline!.x).toBeCloseTo(target!.x,0);expect(outline!.width).toBeCloseTo(target!.width,0);expect((await readState(worker,page.url())).report!.stale).toBe(false);await page.screenshot({path:info.outputPath('finding-locate.png'),caret:'initial'});
 await page.evaluate(()=>{const old=document.querySelector('#unlabeled')!;old.replaceWith(old.cloneNode(true))});await row.getByRole('button',{name:'Locate target',exact:true}).click();await expect(page.getByRole('status')).toContainText('Target unavailable');await expect(page.locator('[data-accesslab-overlay] .outline')).toHaveCount(0);
 await page.getByLabel('Severity',{exact:true}).selectOption('critical');for(const row of await page.locator('.finding').all())await expect(row.locator('.badge')).toHaveText('critical');
});
test('locate distinguishes repeated unnamed controls',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await page.evaluate(()=>{const group=document.createElement('div');group.id='duplicates';for(let i=0;i<2;i++){const b=document.createElement('button');b.style.cssText='width:50px;height:40px;margin-right:20px';group.append(b);}document.querySelector('main')!.prepend(group);});await activate(page);await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).report?.violations.length??0).toBeGreaterThan(0);
 const rows=(await readState(worker,page.url())).report!.violations.filter(f=>f.ruleId==='button-name'&&f.target.join(' ').includes('duplicates'));expect(rows).toHaveLength(2);expect(rows[0].id).not.toBe(rows[1].id);
 for(let i=0;i<2;i++){await page.locator(`[data-finding-id="${rows[i].id}"]`).getByRole('button',{name:'Locate target'}).click();const target=await page.locator('#duplicates button').nth(i).boundingBox();const outline=await page.locator('[data-accesslab-overlay] .outline').boundingBox();expect(outline!.x).toBeCloseTo(target!.x,0);}
});
