import { test,expect } from './fixture';import{readState}from'./state';
test('Tab/Shift+Tab visits are observed, panel ignored and typing stays private',async({page,activate,worker},info)=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('tab',{name:'Inspect',exact:true}).click();await page.getByRole('button',{name:'Enable focus trail'}).click();await page.locator('#good-control').focus();await page.keyboard.press('Tab');await expect(page.locator('#size-23')).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.locator('#good-control')).toBeFocused();let state=await readState(worker,page.url());expect(state.focusTrail.map(o=>o.target)).toEqual(['#good-control','#size-23','#good-control']);
 const count=state.focusVisits;await page.getByRole('button',{name:'Disable focus trail'}).focus();expect((await readState(worker,page.url())).focusVisits).toBe(count);await page.locator('#missing-label').focus();await page.keyboard.type('SECRET_TYPED_VALUE');state=await readState(worker,page.url());expect(JSON.stringify(state.focusTrail)).not.toContain('SECRET_TYPED_VALUE');await page.screenshot({path:info.outputPath('focus-trail.png'),caret:'initial'});await page.getByRole('button',{name:'Clear trail'}).click();expect((await readState(worker,page.url())).focusTrail).toEqual([]);await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.locator('[data-accesslab-overlay] .outline')).toHaveCount(0);await page.locator('#size-23').focus();expect((await readState(worker,page.url())).focusVisits).toBe(0);
});
test('composed focus sees nested open shadows, radio navigation and native modal without intercepting keys',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('tab',{name:'Inspect',exact:true}).click();await page.getByRole('button',{name:'Enable focus trail'}).click();await page.locator('#positive').focus();await page.keyboard.press('Tab');await expect(page.locator('#fixed')).toBeFocused();await page.locator('input[name=choice]').first().focus();await page.keyboard.press('ArrowRight');await expect(page.locator('input[name=choice]').nth(1)).toBeChecked();await page.locator('#open-shadow #shadow-button').focus();await page.keyboard.press('Tab');expect((await readState(worker,page.url())).focusTrail.some(o=>o.target.includes('shadow-button'))).toBe(true);
 await page.locator('#open-modal').click();await expect(page.locator('#modal')).toBeVisible();await page.keyboard.press('Tab');expect((await readState(worker,page.url())).focusTrail.some(o=>o.target==='#close-modal')).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('#modal')).not.toBeVisible();await page.locator('#insert').click();await expect(page.getByRole('button',{name:'Inserted control'})).toBeVisible();await page.getByRole('button',{name:'Inserted control'}).focus();await page.evaluate(()=>document.querySelector('main > button')?.remove());await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.locator('[data-accesslab-overlay] .outline')).toHaveCount(0);
});
