import{test,expect}from'./fixture';import{readState}from'./state';
async function selectDemoRegion(page:import('@playwright/test').Page){await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.getByLabel('Region CSS selector',{exact:true}).fill('#preview-region');await page.getByRole('button',{name:'Select region',exact:true}).click();}
test('@visual selected grayscale/blur previews preserve fixed/sticky/canvas/panel and host filter edits',async({page,activate},info)=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await selectDemoRegion(page);await page.locator('#preview-region').scrollIntoViewIfNeeded();const fixed=await page.locator('.fixed-marker').boundingBox(),header=await page.locator('body > header').boundingBox(),canvas=await page.locator('#canvas').boundingBox();const baseline=await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter);await page.screenshot({path:info.outputPath('preview-baseline.png'),caret:'initial'});
 await page.getByRole('button',{name:'Apply preview'}).click();await expect.poll(async()=>await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter)).toContain('grayscale');expect(await page.locator('.fixed-marker').boundingBox()).toEqual(fixed);expect(await page.locator('body > header').boundingBox()).toEqual(header);expect(await page.locator('#canvas').boundingBox()).toEqual(canvas);await expect(page.getByRole('button',{name:'Reset',exact:true})).toBeVisible();expect(await page.locator('[data-accesslab-root]').evaluate(e=>getComputedStyle(e).filter)).toBe('none');await page.screenshot({path:info.outputPath('preview-grayscale.png'),caret:'initial'});
 await page.getByLabel('Approximation',{exact:true}).selectOption('blur');await page.getByRole('button',{name:'Apply preview'}).click();await expect.poll(async()=>await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter)).toContain('blur(2px)');expect(await page.locator('style[data-accesslab-preview-style]').count()).toBe(1);await page.screenshot({path:info.outputPath('preview-blur.png'),caret:'initial'});
 await page.getByRole('button',{name:'Disable preview'}).click();expect(await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter)).toBe(baseline);await page.getByRole('button',{name:'Apply preview'}).click();await page.evaluate(()=>document.querySelector<HTMLElement>('#preview-region')!.style.filter='invert(1)');await page.getByRole('button',{name:'Disable preview'}).click();expect(await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter)).toBe('invert(1)');await page.screenshot({path:info.outputPath('preview-reset.png'),caret:'initial'});
});
test('preview audit uses baseline and reset during scanning never restores preview',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).report?.generation??0).toBeGreaterThan(0);const baseline=(await readState(worker,page.url())).report!.violations.map(f=>f.ruleId+' '+f.target.join(' '));await selectDemoRegion(page);await page.getByRole('button',{name:'Apply preview'}).click();await page.getByRole('tab',{name:'Audit',exact:true}).click();await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).report?.generation??0).toBeGreaterThan(1);expect((await readState(worker,page.url())).report!.violations.map(f=>f.ruleId+' '+f.target.join(' '))).toEqual(baseline);await expect.poll(async()=>await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter)).toContain('grayscale');await page.getByRole('button',{name:'Run audit',exact:true}).click();await page.getByRole('button',{name:'Reset',exact:true}).click();await expect.poll(async()=>(await readState(worker,page.url())).status).toBe('idle');expect(await page.locator('style[data-accesslab-preview-style]').count()).toBe(0);expect(await page.locator('#preview-region').evaluate(e=>getComputedStyle(e).filter)).toBe('sepia(0.3)');
});
test('root and positioned region preview requests fail explicitly; dynamic unsupported content disables mode',async({page,activate})=>{await page.goto('http://127.0.0.1:4173/');await activate(page);await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.getByLabel('Region CSS selector',{exact:true}).fill('body');await page.getByRole('button',{name:'Select region',exact:true}).click();await page.getByRole('button',{name:'Apply preview'}).click();await expect(page.getByRole('status')).toContainText('html/body');expect(await page.locator('style[data-accesslab-preview-style]').count()).toBe(0);await selectDemoRegion(page);await page.getByRole('button',{name:'Apply preview'}).click();await page.evaluate(()=>{const el=document.createElement('div');el.style.position='fixed';el.textContent='Dynamic unsupported layout';document.querySelector('#preview-region')!.append(el)});await expect(page.getByRole('status')).toContainText('Preview disabled');await expect(page.locator('style[data-accesslab-preview-style]')).toHaveCount(0);});
