import { test,expect,chromium } from '@playwright/test';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
test('production extension native action grants activeTab, runs audit and gives restricted-page feedback',async()=>{
 const profile=await mkdtemp(join(tmpdir(),'accesslab-production-'));const extension=resolve('apps/extension/.output/chrome-mv3');
 const context=await chromium.launchPersistentContext(profile,{channel:'chromium',...(process.env.ACCESSLAB_CHROMIUM?{executablePath:process.env.ACCESSLAB_CHROMIUM}:{}),headless:true,ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging',`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
 try{const worker=context.serviceWorkers()[0]??await context.waitForEvent('serviceworker');const id=new URL(worker.url()).host;const page=await context.newPage();await page.goto('http://127.0.0.1:4173/');const browserCdp=await context.browser()!.newBrowserCDPSession();const targets=await browserCdp.send('Target.getTargets',{filter:[{type:'tab'}]});const target=targets.targetInfos.find(t=>t.url===page.url())?.targetId;expect(target).toBeTruthy();
  const click=()=>browserCdp.send('Extensions.triggerAction',{id,targetId:target!});await click();await expect(page.locator('[data-accesslab-root]')).toHaveCount(1);await click();await expect(page.locator('[data-accesslab-root]')).toHaveCount(1);
  const production=await worker.evaluate(()=>{const api=globalThis as unknown as {chrome:{runtime:{getManifest:()=>{permissions:string[];host_permissions?:string[];content_scripts?:unknown[]}}};__accesslabTestActivate?:unknown};return{manifest:api.chrome.runtime.getManifest(),testHook:typeof api.__accesslabTestActivate};});expect(production.manifest.permissions.sort()).toEqual(['activeTab','scripting','storage']);expect(production.manifest.host_permissions).toBeUndefined();expect(production.manifest.content_scripts).toBeUndefined();expect(production.testHook).toBe('undefined');
  await page.getByRole('button',{name:'Run audit',exact:true}).click();await expect(page.getByRole('status')).toContainText('Scan complete');await page.screenshot({path:'artifacts/production-action.png',caret:'initial'});
  await page.goto('chrome://settings/');await click();const badge=()=>worker.evaluate(async()=>{const api=globalThis as unknown as {chrome:{tabs:{query:(x:object)=>Promise<{id:number}[]>};action:{getBadgeText:(x:object)=>Promise<string>;getTitle:(x:object)=>Promise<string>}}};const tab=(await api.chrome.tabs.query({active:true,currentWindow:true}))[0];return{badge:await api.chrome.action.getBadgeText({tabId:tab.id}),title:await api.chrome.action.getTitle({tabId:tab.id})};});await expect.poll(badge).toMatchObject({badge:'!'});expect((await badge()).title).toContain('ordinary http(s)');
  await page.goto('http://127.0.0.1:4173/');await click();await expect(page.locator('[data-accesslab-root]')).toHaveCount(1);await expect.poll(badge).toEqual({badge:'',title:'Open AccessLab'});await page.getByRole('button',{name:'Close AccessLab'}).click();await expect(page.locator('[data-accesslab-root],[data-accesslab-overlay]')).toHaveCount(0);await browserCdp.detach();
 }finally{await context.close();await rm(profile,{recursive:true,force:true});}
});
