import { test,expect } from './fixture';
import { cpus,totalmem,platform,arch } from 'node:os';
import { writeFile,mkdir } from 'node:fs/promises';
import type { Worker } from '@playwright/test';
import type { PageController } from '../../apps/extension/src/runtime/controller';
async function resources(worker:Worker,url:string,cycle=false){return worker.evaluate(async({url,cycle})=>{
 const api=globalThis as unknown as {chrome:{tabs:{query:(x:object)=>Promise<{id:number;url:string}[]>};scripting:{executeScript:(x:object)=>Promise<{result:{effects:number;ownedAttributeMarkers:number;overlays:number;modules:string[];svg:number;attributes:number;styles:number}}[]>}}};const tab=(await api.chrome.tabs.query({})).find(t=>t.url===url)!;
 const result=await api.chrome.scripting.executeScript({target:{tabId:tab.id},args:[cycle],func:async(cycle:boolean)=>{const c=(globalThis as unknown as {__accesslabController:PageController}).__accesslabController;
 if(cycle){c.overlay.suspend();if(getComputedStyle(c.overlay.host).display!=='none')throw Error('Overlay suspension must hide outlines');c.overlay.resume();await c.enableTargets();await c.enableFocus();c.selectRegion('#preview-region');await c.applyPreview('protanopia');await c.reset();}
 return{effects:c.effects.size,ownedAttributeMarkers:(c as unknown as {ownedAttributes:WeakMap<Element,Set<string>>}).ownedAttributes.get(document.querySelector('#preview-region')!)?.size??0,overlays:c.overlay.count,modules:c.manager.activeIds,svg:document.querySelectorAll('[data-accesslab-color-resource]').length,attributes:[...document.querySelector('#preview-region')!.attributes].filter(a=>a.name.startsWith('data-accesslab-')).length,styles:document.querySelectorAll('[data-accesslab-preview-style]').length};}});return result[0].result;
 },{url,cycle});}
test('twenty target/focus/color-preview/reset cycles return all owned resources to baseline',async({page,worker,activate})=>{
 test.setTimeout(90000);await page.goto('http://127.0.0.1:4173/');await activate(page);const baseline=await resources(worker,page.url());const original=await page.locator('#preview-region').getAttribute('style');
 for(let i=0;i<20;i++)expect(await resources(worker,page.url(),true)).toEqual(baseline);
 expect(await page.locator('#preview-region').getAttribute('style')).toBe(original);await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.getByLabel('Region CSS selector').fill('#preview-region');await page.getByRole('button',{name:'Select region',exact:true}).click();await page.getByLabel('Approximation',{exact:true}).selectOption('protanopia');await page.getByRole('button',{name:'Apply preview',exact:true}).click();await expect(page.locator('[data-accesslab-color-resource]')).toHaveCount(1);await page.getByRole('button',{name:'Close AccessLab'}).click();await expect(page.locator('[data-accesslab-root],[data-accesslab-overlay],[data-accesslab-color-resource],[data-accesslab-preview-style]')).toHaveCount(0);await activate(page);expect(await resources(worker,page.url())).toEqual(baseline);
});
test('five activation timings on 10k-node fixture meet recorded development targets',async({page,activate,context})=>{
 test.setTimeout(90000);await page.goto('http://127.0.0.1:4173/?large');const timings:number[]=[];
 for(let i=0;i<5;i++){const start=performance.now();await activate(page);timings.push(performance.now()-start);await expect(page.getByRole('button',{name:'Close AccessLab'})).toBeVisible();await page.getByRole('button',{name:'Close AccessLab'}).click();await expect(page.locator('[data-accesslab-root]')).toHaveCount(0);}
 const sorted=[...timings].sort((a,b)=>a-b);const measurement={timingsMs:timings,medianMs:sorted[2],worstMs:sorted[4],browser:context.browser()?.version()??'persistent Chromium',platform:platform(),arch:arch(),cpu:cpus()[0]?.model,logicalCpus:cpus().length,memoryBytes:totalmem(),method:'wall-clock worker activation request through validated acknowledgement; excludes navigation/browser launch; five close/reinject cycles on 10,000-button fixture'};
 await mkdir('artifacts',{recursive:true});await writeFile('artifacts/activation-performance.json',JSON.stringify(measurement,null,2));expect(measurement.medianMs).toBeLessThanOrEqual(500);expect(measurement.worstMs).toBeLessThanOrEqual(1500);
});
test('background worker restart preserves content controller and validated state acknowledgement',async({page,activate,worker,context})=>{
 await page.goto('http://127.0.0.1:4173/');await activate(page);const id=new URL(worker.url()).host;
 const docs=await context.newPage();await docs.goto(`chrome-extension://${id}/docs.html`);
 const contextId=()=>docs.evaluate(async()=>{const api=globalThis as unknown as {chrome:{runtime:{getContexts:(filter:object)=>Promise<{contextId:string}[]>}}};return (await api.chrome.runtime.getContexts({contextTypes:['BACKGROUND']}))[0]?.contextId;});const previous=await contextId();expect(previous).toBeTruthy();
 const internals=await context.newPage();await internals.goto('chrome://serviceworker-internals/');await expect(internals.locator('body')).toContainText(`chrome-extension://${id}/`);await internals.getByText('Stop',{exact:true}).click();await expect(internals.locator('body')).toContainText('Running Status: STOPPED');expect(await contextId()).toBeUndefined();
 await internals.getByText('Start',{exact:true}).click();await expect(internals.locator('body')).toContainText('Running Status: RUNNING');await expect.poll(contextId).not.toBe(previous);expect(await contextId()).toBeTruthy();
 const reply=await docs.evaluate(async()=>{const api=globalThis as unknown as {chrome:{tabs:{query:(x:object)=>Promise<{id:number;url:string}[]>;sendMessage:(id:number,x:object,o:object)=>Promise<unknown>}}};const tab=(await api.chrome.tabs.query({})).find(t=>t.url?.startsWith('http://127.0.0.1:4173/'))!;return api.chrome.tabs.sendMessage(tab.id,{schemaVersion:1,requestId:'restart',type:'get-state',payload:{}},{frameId:0});});expect(reply).toMatchObject({type:'ack',payload:{active:true,state:'idle'}});await expect(page.locator('[data-accesslab-root]')).toHaveCount(1);await docs.close();await internals.close();
});
test('only validated preferences survive reload; effects and reports stay transient',async({page,activate,worker})=>{
 await page.goto('http://127.0.0.1:4173/');await worker.evaluate(async()=>{const api=globalThis as unknown as {chrome:{storage:{local:{set:(x:object)=>Promise<void>}}}};await api.chrome.storage.local.set({preferences:{schemaVersion:1,dock:'left',targetThreshold:44,blur:3}});});await activate(page);await expect(page.getByRole('button',{name:'Dock right',exact:true})).toBeVisible();await page.getByRole('button',{name:'Dock right',exact:true}).click();await expect.poll(()=>worker.evaluate(async()=>{const api=globalThis as unknown as {chrome:{storage:{local:{get:(key:string)=>Promise<{preferences:unknown}>}}}};return (await api.chrome.storage.local.get('preferences')).preferences;})).toEqual({schemaVersion:1,dock:'right',targetThreshold:44,blur:3});await page.reload();await expect(page.locator('[data-accesslab-root]')).toHaveCount(0);await activate(page);await page.getByRole('tab',{name:'Inspect',exact:true}).click();await expect(page.getByLabel('Size reference')).toHaveValue('44');await expect(page.getByRole('button',{name:'Enable focus trail',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Inspect targets',exact:true})).toBeVisible();
});
