// @vitest-environment jsdom
import { it, expect } from 'vitest';
import axe from 'axe-core';
import { PageController } from '../../apps/extension/src/runtime/controller';
import { AUDIT_TAGS, findingId, safePageUrl, resolveTarget, type AuditOutput } from '../../packages/modules/src';
import type { AuditReport } from '../../packages/contracts/src';
const report:AuditReport={schemaVersion:1,productVersion:'0.1.0',engine:{name:'axe-core',version:axe.version,tags:AUDIT_TAGS},page:'https://example.test/',viewport:{width:100,height:100},startedAt:new Date().toISOString(),durationMs:1,generation:1,pageRevision:0,stale:false,scope:{topDocument:true,excludedFrames:0,limits:[]},violations:[],needsReview:[]};
it('pinned engine supports configured tags and identities distinguish duplicates',()=>{const tags=new Set(axe.getRules().flatMap(r=>r.tags));for(const tag of AUDIT_TAGS)expect(tags.has(tag)).toBe(true);expect(findingId('x',['#a'],0)).not.toBe(findingId('x',['#a'],1));expect(safePageUrl('https://user:pass@example.test/path?token=secret#private')).toBe('https://example.test/path');});
it('resolves nested open shadow paths without retargeting missing nodes',()=>{const host=document.createElement('div');host.id='host';document.body.append(host);host.attachShadow({mode:'open'}).innerHTML='<button id="inner">Go</button>';expect(resolveTarget(document,['#host','#inner'])?.id).toBe('inner');expect(resolveTarget(document,['#host','#missing'])).toBeNull();host.remove();});
it('reset during delayed audit discards late response',async()=>{let finish:(result:AuditOutput)=>void=()=>{};const c=new PageController(document,()=>new Promise(resolve=>{finish=resolve}));const scan=c.runScan();expect(c.getState().status).toBe('scanning');await c.reset();finish({report,targets:new Map()});await scan;expect(c.getState().status).toBe('idle');expect(c.getState().report).toBeUndefined();await c.close();});
it('failed and timed-out scans are retryable and cancellation clears publication',async()=>{let fail=true;const c=new PageController(document,async()=>{if(fail)throw Error('AUDIT_FAILED fixture');return{report,targets:new Map()}});await c.runScan();expect(c.getState().status).toBe('error');fail=false;await c.runScan();expect(c.getState().report).toBeDefined();await c.close();const slow=new PageController(document,()=>new Promise(()=>{}),5);await slow.runScan();expect(slow.getState().message).toContain('TIMEOUT');await slow.close();});
it('page changes during scan mark the resulting snapshot stale',async()=>{let finish:(result:AuditOutput)=>void=()=>{};const c=new PageController(document,()=>new Promise(resolve=>{finish=resolve}));const scan=c.runScan();c.invalidate('Changed');finish({report,targets:new Map()});await scan;expect(c.getState().report?.stale).toBe(true);await c.close();});
