const sizes=document.querySelector('#size-targets')!;
for(const size of [23,24,25,43,44,45]){const b=document.createElement('button');b.id=`size-${size}`;b.className='size';b.style.width=b.style.height=size+'px';b.style.marginRight='2px';b.textContent=String(size);b.setAttribute('aria-label',`${size} pixel target`);sizes.append(b);}
const shadow=document.querySelector('#open-shadow')!.attachShadow({mode:'open'});const nested=document.createElement('div');nested.id='nested-shadow';shadow.append(nested);const inner=nested.attachShadow({mode:'open'});const shadowButton=document.createElement('button');shadowButton.id='shadow-button';shadowButton.textContent='';inner.append(shadowButton);
const fixed=document.querySelector<HTMLInputElement>('#fixed')!;fixed.addEventListener('change',()=>{for(const id of ['unlabeled','missing-label']){const element=document.getElementById(id)!;if(fixed.checked)element.setAttribute('aria-label',id==='unlabeled'?'Add item':'Example input');else element.removeAttribute('aria-label');}const img=document.getElementById('missing-alt')!;if(fixed.checked)img.setAttribute('alt','Blue square');else img.removeAttribute('alt');document.getElementById('contrast')!.style.color=fixed.checked?'#17283d':'#bbb';shadowButton.textContent=fixed.checked?'Open shadow control':'';});
const modal=document.querySelector<HTMLDialogElement>('#modal')!;document.querySelector('#open-modal')!.addEventListener('click',()=>modal.showModal());document.querySelector('#close-modal')!.addEventListener('click',()=>modal.close());
document.querySelector('#insert')!.addEventListener('click',()=>{history.pushState({},'',`?spa=${Date.now()}`);const b=document.createElement('button');b.textContent='Inserted control';document.querySelector('main')!.append(b);});
const ctx=document.querySelector<HTMLCanvasElement>('#canvas')!.getContext('2d')!;const gradient=ctx.createLinearGradient(0,0,200,0);gradient.addColorStop(0,'red');gradient.addColorStop(.5,'lime');gradient.addColorStop(1,'blue');ctx.fillStyle=gradient;ctx.fillRect(0,0,200,60);
if(new URLSearchParams(location.search).has('large')){const fragment=document.createDocumentFragment();for(let i=0;i<10000;i++){const b=document.createElement('button');b.textContent=`Large fixture ${i}`;fragment.append(b);}document.querySelector('#large')!.append(fragment);}

// This deliberately broken fixture is opt-in, local and always has a safe Escape exit.
const loop=document.querySelector<HTMLElement>('#tab-loop')!,loopInput=document.querySelector<HTMLInputElement>('#loop-input')!,loopOpener=document.querySelector<HTMLButtonElement>('#open-loop')!,loopExit=document.querySelector<HTMLButtonElement>('#exit-loop')!;
const closeLoop=()=>{loop.hidden=true;loopOpener.focus();};loopOpener.addEventListener('click',()=>{loop.hidden=false;loopInput.focus();});loopExit.addEventListener('click',closeLoop);
loop.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeLoop();}else if(event.key==='Tab'&&!fixed.checked){event.preventDefault();loopInput.focus();}});
fixed.addEventListener('change',()=>{loopExit.tabIndex=fixed.checked?0:-1;loopOpener.textContent=fixed.checked?'Open repaired Tab-loop fixture':'Open broken Tab-loop fixture';});
